site_name: python-app
site_description: Main documentation for python-app
repo_url: https://github.com/vmvarela/python-app
edit_url: edit/master/docs

plugins:
  - techdocs-core

nav:
  - Overview:
    - Getting started: docs/index.md
