apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-app
spec:
  ingressClassName: nginx
  rules:
  - host: "python-app.test.local"
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: python-app-svc
              port:
                number: 8080
